### ISSUE TITLE
Limitar texto para não extrapolar o espaço disponível

### ISSUE THREAD

**Issue by lpirola** [nossas/vivos-em-nos#105]
![image](https://cloud.githubusercontent.com/assets/14948/25645851/efd93e20-2f88-11e7-89ee-bdadfd2a79ad.png)

**Comment by gabrielrtakeda** [comment]
Talvez a issue **Criar contador de caracteres que mostre o limite de cada campo** #101 já resolva esse problema.

**Comment by igr-santos** [comment]
@lpirola será que devemos limitar também no estilo (CSS)?
