### ISSUE TITLE
Adicionar filtro na query da lista de homenagem em destaque na home

### ISSUE THREAD

**Issue by lpirola** [nossas/vivos-em-nos#115]
Para que apenas algumas homenagens  selecionadas sejam apresentadas. 

Será necessário adicionar um campo da tabela de memorias chamado featured_to_site

**Comment by gabrielrtakeda** [comment]
Como será feita a "marcação" da memória desejada? Update diretamente no banco atualizando a coluna `featured_to_site`?

**Comment by lpirola** [comment]
exatamente @gabrielrtakeda
