### ISSUE TITLE
Adicionar botões de compartilhar nas redes

### ISSUE THREAD

**Issue by lpirola** [nossas/vivos-em-nos#12]
Utilizar: Facebook, Twitter e Whatsapp

https://simpleicons.org/

**Comment by gabrielrtakeda** [comment]
Os botões mencionados já foram adicionados, cada um com seu arquivo svg:
https://github.com/nossas/vivos-em-nos/blob/master/src/views/pages/memory-victim.js#L51-L58

**Comment by gabrielrtakeda** [comment]
Vou criar a integração com as API's de cada rede social.
Mas será necessário o SSR da página da homenagem pra que seja feito o crawler do conteúdo.

**Comment by gabrielrtakeda** [comment]
Vou trocar também os arquivos svg's usados hoje, pra ter uma maior flexibilidade em alterar o fundo.. Vou usar só os ícones do https://simpleicons.org/ e colocar um background com css. Melhor 🙂

**Comment by gabrielrtakeda** [comment]
Rebase 👇
