### ISSUE TITLE
Adicionar campo de slug da memoria e trocar rota final

### ISSUE THREAD

**Issue by lpirola** [nossas/vivos-em-nos#129]
Personalizar a URL para ter o nome do homenageado: trocar de "memory/20" para  "http://vivosemnos.org/vinicius-silva"

**Comment by gabrielrtakeda** [comment]
E se ocorrer de conflitar o slug? Ou seja, pessoas com o mesmo nome e sobrenome..

**Comment by bnd-operator** [comment]
Sim,por isso q ele acho q ele deve ser único. Para ser mais fácil acho q
vale só implementar o slug no banco.

**Comment by lpirola** [comment]
@gabrielrtakeda encontrei um problema ao tentar criar uma homenagem quando utilizando esse branch, pode dar uma conferida?
