### ISSUE TITLE
Ajustes gerais de texto pré-v1.1

### ISSUE THREAD

**Issue by lpirola** [nossas/vivos-em-nos#175]
**Home espanhol**
- [x] Linkar logo "VivosEmNosotros" no rodapé para o Facebook (fb.com/vivosennos)

**Geral**
- [x] Tirar "seguir" do menu mobile, home desktop e menu das interna
- [x] Tirar "compartilhar" do menu mobile, home desktop e menu das interna
- [x] Trocar o nome do bloco "homenagens" para "Últimas Homenagens"

**"Visualizar Homenagem Completa"**
- [x] Inserir um "texto preset"  "Quando eu penso em FNAME eu lembro de..." antes do segundo espaço de texto.
- [x] Quando o usuário não tiver inserido nenhuma imagem na galeria, tirar o título "Galeria de Imagens" da página de visualização da homenagem
- [x] Ao final da página, após o botão de "enviar comentário", inserir frase: "Denunciar este conteúdo" linkada pra mailto:contato@instintodevida.org
- [x] Subir a área dos comentários publicados, deve ficar entre o compartilhamento e "Quer contribuir com essa homenagem?" 

**Shares:**
- [x] [Share de Facebook] Ajustar o logo (tá cortado)
- [x] [Share de Twitter] trocar texto-padrão (preset) 
  - DE: "Acabei de criar uma homenagem para  ngelo Marcos Machado. Confira em https://vivosemnos.org/angelo-marcos-machado"
  - PARA: 
    - Port: "FNAME e tantos outros seguem #VivosEmNós e essa página é em sua homenagem. Veja aqui [link personalizado]"
    - Esp:  "FNAME y tantos otros siguen #VivosEnNosotros y esa pagina es un homenaje. Véala aquí [link personalizado] 

**Rodapé**
- [x] Trocar a logo do "Instinto de Vida" para a versão rosa (arquivo em png tá "pinnado" no canal do slack)
- [x] Linkar a logo do "Vivos Em Nós" à página de facebook (www.fb.com/vivosennos)

**Mail**
- [x] Trocar o texto "Atenciosamente, Equipe Vivos Em Nós" para: "Saludos, Equipo Vivos En Nosotros"
- [x] Tem frase repetida em português no meio da mensagem abaixo. Tirar o que está destacado:
  - Ese mail fue enviado porque fue creado un homenaje en el sitio **Este email foi enviado porque foi criada uma homenagem no site** www.vivosennosotros.org. Si no fue usted que lo creó, no considere ese mensaje.

**Comment by gabrielrtakeda** [comment]
> Inserir um "texto preset" "Quando eu penso em FNAME eu lembro de..." antes do segundo espaço de texto.

Não gosto muito de ter **FNAME** no label mas, ok...
