### ISSUE TITLE
Limitar o campo victim_remember_text em 63 caracteres

### ISSUE THREAD

**Issue by lpirola** [nossas/vivos-em-nos#54]
Estou usando esse tamanho por ser o limite permitido para o tamanho máximo de uma url que é 255.

**Comment by igr-santos** [comment]
@lpirola não entendi muito bem, o campo `victimRemenberText` é um campo com tamanho máximo de 500 caracteres, assim é sugerido pelo guide que temos, você está falando sobre o campo `victimGoodWords`?

**Comment by lpirola** [comment]
@igr-santos isso, era sobre esse mesmo. Criei outra issue #116
