### ISSUE TITLE
Melhorar imagens da galeria quando upload é feito

### ISSUE THREAD

**Issue by lpirola** [nossas/vivos-em-nos#86]

**Comment by gabrielrtakeda** [comment]
| **estado inicial**                                                                                                                                                      | **preenchido**                                                                                                                                                          |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="310" alt="screen shot 2017-05-04 at 4 16 33 pm" src="https://cloud.githubusercontent.com/assets/5435389/25721114/b3f0f002-30e5-11e7-9340-0ba30897f82c.png"> | <img width="307" alt="screen shot 2017-05-04 at 4 20 30 pm" src="https://cloud.githubusercontent.com/assets/5435389/25721118/ba7e6f30-30e5-11e7-8386-43903993a33b.png"> |
