### ISSUE TITLE
Aumentar o uso do grid do bulma

### ISSUE THREAD

**Issue by lpirola** [nossas/vivos-em-nos#95]
http://bulma.io/documentation/grid/columns/

**Comment by lpirola** [comment]
@gabrielrtakeda vou tentar usar o grid e aplicar essa versão desktop na home.

![18297064_10212994592447890_867761148_o](https://cloud.githubusercontent.com/assets/14948/25711746/092f9be2-30c6-11e7-9ac3-d01d33e72308.png)

**Comment by gabrielrtakeda** [comment]
rebase 👇

**Comment by gabrielrtakeda** [comment]
ok @lpirola, dei um tapa no componente `<MemorySummary />` pro texto ficar mais flexível também..

em específico:
<img width="316" alt="screen shot 2017-05-04 at 2 56 33 pm" src="https://cloud.githubusercontent.com/assets/5435389/25717772/ea5ed8ae-30d9-11e7-904d-77268146ca0e.png">

com os textos no limite. `victimHistory` e `victimRememberText` com 200 e 500 chars respectivamente.

**Comment by gabrielrtakeda** [comment]
agora não vai ter margem de erro pro layout quebrar 🙂
